[package]
name = "yohei_yayoi/resulty"
description = "âš¡ Type-safe error handling for Luau"
version = "1.0"
license = "MIT"
authors = ["yohei_yayoi"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dev-dependencies]
